# This workflow will do a clean installation of node dependencies, cache/restore them, build the cv pdf file.
name: md to pdf CI

# Disable the workflow
on:
  push:
    branches: [ "_disabled" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build the CV PDF
        run: yarn pdf

      - name: Make dist directory
        run: mkdir -p dist

      - name: Move the pdf to the dist dir
        run: mv build/cv.pdf dist/cv-mohamad-eldhemy.pdf

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Mohamad Eldhemy
          author_email: imdhemy@gmail.com
          message: "Update CV"
          add: "dist/cv-mohamad-eldhemy.pdf"
